### PR TITLE
Update team

### PR DESCRIPTION
**Pull request by david-driscoll**
Removed some inactive members from the members page, also I've added in the following team members from the existing pull requests.  If folks can make sure that these guys are still ones we should have in this list or not.

cc @DustinCampbell @filipw @peterblazejewicz  If you guys can help ensure this list looks right, I can come back in and move things around as needed.

* @DustinCampbell
* @dmccaffery
* @rajkumar42
* @troydai
* @gregg-miskelly
* @caslan

The following have not been added, but can be added.  I'm just trying to go by contributions, plus recent contriutions as well. (And may be failing)
* @Muchiachio
* @Pilchie
* @SamuelEnglard
* @Spinarooni
* @mattwar
* @sjrmanning
* @wesrupert

**Note to anyone that was removed**: This is not personal we're just trying to keep the list up to date and organized.  We welcome your contributions again in the future if you do return!

### CODE REVIEW

**Comment by david-driscoll** [comment]
closes #67 #69

**Comment by DustinCampbell** [comment]
@troydai, do you want to be listed? I think you've been pulled off onto other things, right?

@gregg-miskelly, @rajkumar42, and @caslan are specifically part of the debugger team and not contributing to OmniSharp as a whole. Are you guys interested in being listed on http://www.omnisharp.net? It's OK if you do or don't want to be, I just wanted to check.

@Pilchie and @mattwar probably shouldn't be added (unless they start doing stuff! :smile:)

**Comment by gregg-miskelly** [comment]
I don't have a strong preference. I certainly don't mind being added at all, but since I haven't been contributing to the editor side of the C# extension I certainly wouldn't feel like I was being slighted if I was left off.

**Comment by rajkumar42** [comment]
I don't mind either way as long as I am allowed to contribute :)

**Comment by troydai** [comment]
Yeah, I'm pulled off. But I don't mind. I still see chances for me to contribute anyway :).

**Comment by Pilchie** [comment]
I'm a pointy-haired-boss and don't write code these days.  I don't need to be listed...

**Comment by david-driscoll** [comment]
@OmniSharp/all going go with this change sometime tomorrow, unless there are any stern objections.

**Comment by ctolkien** [comment]
Agreed, I'm not very active anymore - should also be cut from the Omnisharp GH org?

**Comment by filipw** [comment]
@david-driscoll  yeah the github organization definitely needs a similar review

**Pull request merged**
