### PR TITLE
Update team information: @chuckries

### PR DESCRIPTION
**Pull request by peterblazejewicz**
/cc
@chuckries
Mind reviewing? Twitter handle maybe?

See: https://git.io/vK4iS

image

Thanks!

### CODE REVIEW

**Comment by chuckries** [comment]
twitter is chuckguy55 if you'd like to add it.

**Comment by chuckries** [comment]
:+1:

**Comment by chuckries** [comment]
@peterblazejewicz Anything ever happen with this?

**Comment by david-driscoll** [comment]
I never noticed it (basically)!  Sorry about that.

**Comment by peterblazejewicz** [comment]
@david-driscoll NP. If you have time there are others PRs pending here, I have not merge rights on this repo. Thanks!

**Pull request merged**
